const data = [
    {
        id: 3,
        name: "hb",
        title: "韩版",
        text: "一&nbsp;&nbsp;结婚是一个幸福的决定，是两个有情的牵手，是三生石上不变的承诺，是四世同堂最美的梦境。",
        mainInfo: [
            {
                id: 1,
                url: "https://s.hunlihu.com/html/3Q33vffRvR",

                title1: "韩式简约婚礼",
                time1: "2021年8月8日",
                style: "翻页",
                sum: "20张",
                money: "20",
                hot: 0,
                type: "韩版",
            },
            {
                id: 2,
                url: "https://s.hunlihu.com/html/RKKfRK3fv1",
                src: "https://s.hunlihu.com/share/e2941ab37dd94cdab8b4e6bae6406f1b.jpg",
                title1: "素雅纯色崽崽❤长页ღ",
                time1: "2021年1月8日",
                style: "长页",
                sum: "20张",
                money: "50",
                hot: 0,
                type: "韩版",
            },
            {
                id: 3,
                url: "https://s.hunlihu.com/html/3Q33Qe7veQ",
                title1: "韩式浅粉简约ins",
                time1: "2021年8月9日",
                style: "翻页",
                sum: "13张",
                money: "20",
                hot: 0,
                type: "韩版",
            },
            {
                id: 4,
                url: "https://s.hunlihu.com/html/3Q33eeedff",
                title1: "雾霭蓝简约ins",
                time1: "2021年2月2日",
                style: "翻页",
                sum: "12张",
                money: "20",
                hot: 0,
                type: "韩版",
            },
            {
                id: 5,
                url: "https://s.hunlihu.com/html/3Q13f1eRKR",
                title1: "简约文艺杂志风",
                time1: "2021年5月26日",
                style: "翻页",
                sum: "22张",
                money: "20",
                hot: 0,
                type: "韩版",
            },
            {
                id: 6,
                url: "https://s.hunlihu.com/html/373KKdRved",
                title1: "时尚唯美韩式",
                time1: "2021年5月20日",
                style: "翻页",
                sum: "21张",
                money: "20",
                hot: 0,
                type: "韩版",
            },
            {
                id: 7,
                url: "https://s.hunlihu.com/html/3KKv3777dv",
                title1: "韩式时尚杂志",
                time1: "2021年12月6日",
                style: "翻页",
                sum: "1张",
                money: "40",
                hot: 0,
                type: "韩版",
            },
            {
                id: 8,
                url: "https://s.hunlihu.com/html/RK77QvK31d",
                title1: "简雅韩式❤长页",
                time1: "2021年12月8日",
                style: "长页",
                sum: "17张",
                money: "30",
                hot: 0,
                type: "韩版",
            },
            {
                id: 9,
                url: "https://s.hunlihu.com/html/RKQdfQefRe",
                title1: "囍历❤长页",
                time1: "2021年11月6日",
                style: "长页",
                sum: "13张",
                money: "30",
                hot: 0,
                type: "韩版",
            },
            {
                id: 10,
                url: "https://s.hunlihu.com/html/RKffeKef3R",
                title1: "手绘卡通系❤长页",
                time1: "2021年1月2日",
                style: "长页",
                sum: "18张",
                money: "50",
                hot: 0,
                type: "韩版",
            },
            {
                id: 11,
                url: "https://s.hunlihu.com/html/RKReeRdK7f",
                title1: "青葡萄❤长页",
                time1: "2021年1月2日",
                style: "长页",
                sum: "14张",
                money: "50",
                hot: 0,
                type: "韩版",
            },
            {
                id: 12,
                url: "https://s.hunlihu.com/html/RQKee7dKeQ",
                title1: "韩式撞色❤海报",
                time1: "2021年1月7日",
                style: "单页",
                sum: "1张",
                money: "10",
                hot: 0,
                type: "韩版",
            },
            {
                id: 13,
                url: "https://s.hunlihu.com/html/Rv7K7Qfe1f",
                title1: "温暖纪事",
                time1: "2021年9月6日",
                style: "翻页",
                sum: "17张",
                money: "40",
                hot: 0,
                type: "韩版",
            },
            {
                id: 14,
                url: "https://s.hunlihu.com/html/7Kd7eeRQRR",
                title1: "Fall in love",
                time1: "2021年1月5日",
                style: "翻页",
                sum: "14张",
                money: "50",
                hot: 0,
                type: "韩版",
            },
            {
                id: 15,
                url: "https://s.hunlihu.com/html/vvfdeKfQdR",
                title1: "以爱之名崽崽❤❤长页ღ",
                time1: "2021年11月7日",
                style: "长页",
                sum: "19张",
                money: "30",
                hot: 0,
                type: "韩版",
            },
            {
                id: 16,
                url: "https://s.hunlihu.com/html/vK11KQfR7d",
                title1: "韩式崽崽ins风❤❤ღ",
                time1: "2021年1月9日",
                style: "翻页",
                sum: "16张",
                money: "60",
                hot: 0,
                type: "韩版",
            },
            {
                id: 17,
                url: "https://s.hunlihu.com/html/7d7K7vfvev",
                title1: "月亮创意时尚",
                time1: "2021年7月7日",
                style: "翻页",
                sum: "17张",
                money: "40",
                hot: 0,
                type: "韩版",
            },
            {
                id: 18,
                url: "https://s.hunlihu.com/html/vKfeK7ve7f",
                title1: "青青子衿",
                time1: "2021年7月8日",
                style: "翻页",
                sum: "14张",
                money: "40",
                hot: 0,
                type: "韩版",
            },
            {
                id: 19,
                url: "https://s.hunlihu.com/html/3d1dvQQ7fQ",
                title1: "韩式信封❤海报",
                time1: "2021年8月9日",
                style: "单页",
                sum: "1张",
                money: "10",
                hot: 0,
                type: "韩版",
            },
            {
                id: 20,
                url: "https://s.hunlihu.com/html/331vveRe37",
                title1: "文艺轻奢❤海报",
                time1: "2021年1月21日",
                style: "单页",
                sum: "1张",
                money: "10",
                hot: 0,
                type: "韩版",
            },
            {
                id: 21,
                url: "https://s.hunlihu.com/html/3313ee3Rvv",
                title1: "绝美韩式❤海报",
                time1: "2021年9月26日",
                style: "单页",
                sum: "1张",
                money: "10",
                hot: 0,
                type: "韩版",
            },
            {
                id: 22,
                url: "https://s.hunlihu.com/html/vQKvdKv7Q3",
                title1: "淡紫卡片❤延期海报",
                time1: "2021年1月30日",
                style: "单页",
                sum: "1张",
                money: "10",
                hot: 0,
                type: "韩版",
            },
            {
                id: 23,
                url: "https://s.hunlihu.com/html/v7e31v3f1Q",
                title1: "撞色莫兰迪",
                time1: "2021年2月8日",
                style: "翻页",
                sum: "8张",
                money: "30",
                hot: 0,
                type: "韩版",
            },
            {
                id: 24,
                url: "https://s.hunlihu.com/html/v7Kdf337R7",
                title1: "给你我的蓝",
                time1: "2021年3月23日",
                style: "翻页",
                sum: "15张",
                money: "20",
                hot: 0,
                type: "韩版",
            },
            {
                id: 25,
                url: "https://s.hunlihu.com/html/7d7eKR7vQR",
                title1: "高端时尚大气文艺",
                time1: "2021年1月25日",
                style: "长页",
                sum: "26张",
                money: "40",
                hot: 0,
                type: "韩版",
            },
            {
                id: 26,
                url: "https://s.hunlihu.com/html/vQ1eevevd3",
                title1: "韩式典雅质感❤海报",
                time1: "2021年11月21日",
                style: "单页",
                sum: "1张",
                money: "10",
                hot: 0,
                type: "韩版",
            },
            {
                id: 27,
                url: "https://s.hunlihu.com/html/vQRf3e1deR",
                title1: "灰绿便签❤海报",
                time1: "2021年6月28日",
                style: "单页",
                sum: "1张",
                money: "10",
                hot: 0,
                type: "韩版",
            },
            {
                id: 28,
                url: "https://s.hunlihu.com/html/vQRf7R11KR",
                title1: "淡紫卡片❤海报",
                time1: "2021年1月28日",
                style: "单页",
                sum: "1张",
                money: "10",
                hot: 0,
                type: "韩版",
            },
            {
                id: 29,
                url: "https://s.hunlihu.com/html/vQveve13ee",
                title1: "手绘简约淡雅❤海报",
                time1: "2021年11月6日",
                style: "单页",
                sum: "1张",
                money: "10",
                hot: 0,
                type: "韩版",
            },
            {
                id: 30,
                url: "https://s.hunlihu.com/html/7Rd1fQ77fQ",
                title1: "手绘萌咪",
                time1: "2021年8月6日",
                style: "翻页",
                sum: "9张",
                money: "30",
                hot: 0,
                type: "韩版",
            },
            {
                id: 31,
                url: "https://s.hunlihu.com/html/3KeRvve17f",
                title1: "清新ins韩式时尚❤长页",
                time1: "2021年6月6日",
                style: "长页",
                sum: "12张",
                money: "20",
                hot: 0,
                type: "韩版",
            },
        ],
    },
];
